Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Layout/MultilineMethodCallIndentation:
#   EnforcedStyle: indented

# Style/SpaceInsideBrackets:
#   Enabled: false

# Style/SpaceInsideParens:
#   Enabled: false
